// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectChicago.Audit.Core.Persistence;

#nullable disable

namespace ProjectChicago.Audit.Core.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectChicago.Audit.Core.Persistence.AuditEntry", b =>
                {
                    b.Property<Guid>("AuditEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActionCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ActorDisplayName")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AuditedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CausationId")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ChangedFields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawEventPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceEventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SummaryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("AuditEntryId");

                    b.HasAlternateKey("EventId")
                        .HasName("AK_AuditEntries_EventId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditEntries_CorrelationId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_AuditEntries_OccurredAt");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("IX_AuditEntries_TraceId");

                    b.HasIndex("ActorUserId", "AuditedAtUtc")
                        .HasDatabaseName("IX_AuditEntries_Actor_AuditedAt");

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc")
                        .HasDatabaseName("IX_AuditEntries_EntityTypeId_OccurredAt");

                    b.HasIndex("SourceService", "Action", "AuditedAtUtc")
                        .HasDatabaseName("IX_AuditEntries_Service_Action_AuditedAt");

                    b.ToTable("AuditEntries", "audit");
                });

            modelBuilder.Entity("ProjectChicago.Shared.Inbox.InboxMessage", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CausationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LeasedUntilUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ProcessingCompletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("MessageId");

                    b.HasIndex("Status", "LeasedUntilUtc")
                        .HasDatabaseName("IX_InboxMessages_Status_LeasedUntilUtc");

                    b.ToTable("InboxMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
