namespace ProjectChicago.Audit.Core.Persistence;

/// <summary>
/// Append-only audit entry capturing every Client/Project/Task/User mutation with traceability
/// (ADR-0016, AUDIT-001..008). This model is immutable: INSERT only, never UPDATE/DELETE.
/// </summary>
public class AuditEntry
{
    /// <summary>
    /// Unique audit record identifier (GUID), generated by Audit service. Primary key.
    /// </summary>
    public required Guid AuditEntryId { get; init; }

    /// <summary>
    /// Integration event message ID for idempotent consumption (ASYNC-005, AUDIT-004).
    /// Unique constraint enforces one audit entry per event.
    /// </summary>
    public required string EventId { get; init; }

    /// <summary>
    /// The business entity type affected (Client, Project, Task, ApplicationUser, etc.).
    /// See AuditEntityTypes for standard values (AUDIT-001).
    /// </summary>
    public required string EntityType { get; init; }

    /// <summary>
    /// The business entity's GUID identifier.
    /// </summary>
    public required Guid EntityId { get; init; }

    /// <summary>
    /// The action performed on the entity (Created, Updated, StatusChanged, etc.).
    /// See AuditActions for common values (AUDIT-003); string to allow extension without versioning.
    /// </summary>
    public required string Action { get; init; }

    /// <summary>
    /// Machine-readable action category for filtering/reporting (WRITE, TRANSITION, ASSIGN, ARCHIVE).
    /// Derived from Action during audit entry construction.
    /// </summary>
    public required string ActionCategory { get; init; }

    /// <summary>
    /// The human user ID performing the action; null for system/service-initiated mutations (AUDIT-002, AUDIT-006).
    /// </summary>
    public Guid? ActorUserId { get; init; }

    /// <summary>
    /// The actor type: User, System, Service, Anonymous (AuditActorTypes, AUDIT-002, AUDIT-006).
    /// </summary>
    public required string ActorType { get; init; }

    /// <summary>
    /// Human-readable actor identifier (username, service name). For troubleshooting only, not authoritative (AUDIT-006).
    /// </summary>
    public string? ActorDisplayName { get; init; }

    /// <summary>
    /// The bounded service that published the mutation event (Crm, Identity, Notification, Workflow; AuditSourceServices).
    /// </summary>
    public required string SourceService { get; init; }

    /// <summary>
    /// The integration event contract name/type that generated this audit entry (e.g., Crm.ClientCreated).
    /// </summary>
    public required string SourceEventType { get; init; }

    /// <summary>
    /// Timestamp when the business event actually occurred (originating service UTC time; AUDIT-002).
    /// </summary>
    public required DateTime OccurredAtUtc { get; init; }

    /// <summary>
    /// Timestamp when the audit entry was persisted (Audit service UTC time; AUDIT-002).
    /// May differ from OccurredAtUtc due to Service Bus processing latency.
    /// </summary>
    public required DateTime AuditedAtUtc { get; init; }

    /// <summary>
    /// OpenTelemetry W3C trace context identifier for linking to distributed logs (ADR-0021, AUDIT-007).
    /// </summary>
    public required string TraceId { get; init; }

    /// <summary>
    /// Correlation ID tracing the entire user request flow (gateway → API → Service Bus → downstream).
    /// Originates at the gateway; preserved across services (ADR-0010, AUDIT-007).
    /// </summary>
    public required string CorrelationId { get; init; }

    /// <summary>
    /// Causation ID pointing to the immediate cause (parent message/request ID); null for root-level actions.
    /// Allows following chains of causality (ADR-0010, AUDIT-007).
    /// </summary>
    public string? CausationId { get; init; }

    /// <summary>
    /// JSON array of field names that changed, e.g. ["Status", "Priority"] (AUDIT-002).
    /// Field names only, never values. Always safe to include.
    /// </summary>
    public required string ChangedFields { get; init; }

    /// <summary>
    /// JSON object mapping field names to their previous values (only for fields approved as safe to disclose).
    /// Null if no before-state or values not captured (AUDIT-002, AUDIT-008, PRIV-002).
    /// </summary>
    public string? PreviousValues { get; init; }

    /// <summary>
    /// JSON object mapping field names to their new values (only for fields approved as safe to disclose).
    /// Null if values not captured (AUDIT-002, AUDIT-008, PRIV-002).
    /// </summary>
    public string? NewValues { get; init; }

    /// <summary>
    /// Human-readable summary of the mutation for UI display (e.g., "Status changed from Lead to Prospect").
    /// </summary>
    public string? SummaryDescription { get; init; }

    /// <summary>
    /// The complete integration event payload received from Service Bus, redacted per AuditSensitiveFieldNames
    /// (AUDIT-008, PRIV-002). Stored for forensics/reconstruction without exposing secrets/tokens/credentials.
    /// </summary>
    public required string RawEventPayload { get; init; }

    /// <summary>
    /// Row version for optimistic concurrency (SQL Server). Prevents accidental UPDATE (though INSERT-only design
    /// enforces this at the application layer).
    /// </summary>
    public byte[]? RowVersion { get; init; }
}
