<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>eaa3efe9-a747-4417-9b8e-96dd4ed90d36</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectChicago.Crm\ProjectChicago.Crm.csproj" />
    <ProjectReference Include="..\ProjectChicago.Crm.Functions\ProjectChicago.Crm.Functions.csproj" />
    <ProjectReference Include="..\ProjectChicago.Identity\ProjectChicago.Identity.csproj" />
    <ProjectReference Include="..\ProjectChicago.Identity.Functions\ProjectChicago.Identity.Functions.csproj" />
    <ProjectReference Include="..\ProjectChicago.Audit\ProjectChicago.Audit.csproj" />
    <ProjectReference Include="..\ProjectChicago.Audit.Functions\ProjectChicago.Audit.Functions.csproj" />
    <ProjectReference Include="..\ProjectChicago.Gateway\ProjectChicago.Gateway.csproj" />
  </ItemGroup>

</Project>
